version: "3.9"
services:
  api:
    container_name: api-lyts
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    links:
      - db
  db:
    container_name: db_lyts
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
